import Head from "next/head";
import { useState } from "react";
import Dropdown from '../components/dropdowns/Dropdown';
import Header from "../components/headers/Header";

export default function Home() {
	
	
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="p-5 bg-blue-500 text-white flex justify-between items-center">
				<div className="text-3xl font-bold">Next.js</div>
				<div className="cursor-pointer">
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="30" height="30"><path fill="none" d="M0 0h24v24H0z"/><path fill="white" d="M3 4h18v2H3V4zm6 7h12v2H9v-2zm-6 7h18v2H3v-2z"/></svg>
				</div>
			</div>

			<div className="m-4 h-96 rounded-xl overflow-hidden">
				<img src="https://www.bora.com/fileadmin/website_content/Erleben/Cooking/55_Team_Edition/Rezeptbilder/55_TeamEdition_Canada_Halloumi-Burger.jpg" alt="" className="w-full" />
			</div>

			<div className="px-4 flex space-x-2">
				<div className="w-1/2 h-96 bg-red-400 rounded-xl"></div>
				<div className="w-1/2 h-96 bg-green-400 rounded-xl"></div>
			</div> */}

      <Header/>
    </div>
  );
}
